site_name: EduManage - Documentación Técnica
site_description: Sistema integral de gestión educativa
site_author: Nombre Apellido
site_url: https://tu-usuario.github.io/despr1_4_mkdocs/

repo_name: tu-usuario/despr1_4_mkdocs
repo_url: https://github.com/tu-usuario/despr1_4_mkdocs
edit_uri: edit/main/docs/

theme:
  name: material
  language: es
  favicon: images\favicon.ico
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - content.code.annotate
    - content.code.copy
  palette: 
    # Palette toggle for light mode - scheme: default 
    toggle: 
    icon: material/brightness-7  
    name: Switch to dark mode 
# Palette toggle for dark mode - scheme: slate 
  toggle: 
    icon: material/brightness-4 
    name: Switch to light mode

plugins:
  - search:
      lang: es
  - mermaid2:
      arguments:
        theme: base

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:mermaid2.fence_mermaid
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - md_in_html
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - mdx_math:
      enable_dollar_delimiter: True
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Inicio: index.md
  - Instalación: instalacion.md
  - Autenticación:
      - Sistema de Login: ./modulos/login.md
      - Configuración OAuth: ./modulos/oauth.md
  - Dashboard:
      - Vista General: ./modulos/dashboard.md
      - Métricas: ./modulos/metricas.md
      - Configuración: ./modulos/settings.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/tu-usuario
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/tu-usuario
  extra_javascript:
    - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.4/MathJax.js?config=TeX-MML-AM_HTMLorMML
